### ISSUE TITLE
error compiling fanuc_driver_exp from source

### ISSUE THREAD

**Issue by ReedAJacobsen** [gavanderhoorn/ktransw_py#15]
I have attempted to compile <del>the driver</del> `fanuc_driver_exp` from source (following the instructions in the readme), however the ninja build fails (All other commands before this appear to work correctly).  Zipped version of Rossum work-space after all commands run is also attached. Any hints?

```
C:\Users\Controls\Rossum_ws\build>ninja -v
[1/22] ktransw.cmd -q -MM -MP -MT C:\Users\Controls\Rossum_ws\build\ros_state.pc -MF C:\Users\Controls\Rossum_ws\build\ros_state.pc.d --ktrans="C:\Program Files (x86)\Fanuc\WinOLPC\bin\ktrans.exe" /I"C:\Users\Controls\Rossum_ws\fanuc_driver_exp\include" /I"C:\Users\Controls\Rossum_ws\libindlog\include" /I"C:\Users\Controls\Rossum_ws\libsimplemsg\include" /I"C:\Users\Controls\Rossum_ws\KUnit\include" /I"C:\Users\Controls\Rossum_ws\libmathex\include" /I"C:\Users\Controls\Rossum_ws\libstdex\include" /I"C:\Program Files (x86)\Fanuc\WinOLPC\Versions\V830-1\support" C:\Users\Controls\Rossum_ws\fanuc_driver_exp\src\ros_state.kl /ver V8.30-1 /config "C:\Users\Controls\Rossum_ws\fanuc_driver_exp"
FAILED: C:/Users/Controls/Rossum_ws/build/ros_state.pc
ktransw.cmd -q -MM -MP -MT C:\Users\Controls\Rossum_ws\build\ros_state.pc -MF C:\Users\Controls\Rossum_ws\build\ros_state.pc.d --ktrans="C:\Program Files (x86)\Fanuc\WinOLPC\bin\ktrans.exe" /I"C:\Users\Controls\Rossum_ws\fanuc_driver_exp\include" /I"C:\Users\Controls\Rossum_ws\libindlog\include" /I"C:\Users\Controls\Rossum_ws\libsimplemsg\include" /I"C:\Users\Controls\Rossum_ws\KUnit\include" /I"C:\Users\Controls\Rossum_ws\libmathex\include" /I"C:\Users\Controls\Rossum_ws\libstdex\include" /I"C:\Program Files (x86)\Fanuc\WinOLPC\Versions\V830-1\support" C:\Users\Controls\Rossum_ws\fanuc_driver_exp\src\ros_state.kl /ver V8.30-1 /config "C:\Users\Controls\Rossum_ws\fanuc_driver_exp"
  File "C:\ktransw_py-0.2.2\\ktransw.py", line 246
    except ValueError, e:
                     ^
SyntaxError: invalid syntax
[2/22] ktransw.cmd -q -MM -MP -MT C:\Users\Controls\Rossum_ws\build\libssock.pc -MF C:\Users\Controls\Rossum_ws\build\libssock.pc.d --ktrans="C:\Program Files (x86)\Fanuc\WinOLPC\bin\ktrans.exe" /I"C:\Users\Controls\Rossum_ws\fanuc_driver_exp\include" /I"C:\Users\Controls\Rossum_ws\libindlog\include" /I"C:\Users\Controls\Rossum_ws\libsimplemsg\include" /I"C:\Users\Controls\Rossum_ws\KUnit\include" /I"C:\Users\Controls\Rossum_ws\libmathex\include" /I"C:\Users\Controls\Rossum_ws\libstdex\include" /I"C:\Program Files (x86)\Fanuc\WinOLPC\Versions\V830-1\support" C:\Users\Controls\Rossum_ws\fanuc_driver_exp\src\libssock.kl /ver V8.30-1 /config "C:\Users\Controls\Rossum_ws\fanuc_driver_exp"
FAILED: C:/Users/Controls/Rossum_ws/build/libssock.pc
ktransw.cmd -q -MM -MP -MT C:\Users\Controls\Rossum_ws\build\libssock.pc -MF C:\Users\Controls\Rossum_ws\build\libssock.pc.d --ktrans="C:\Program Files (x86)\Fanuc\WinOLPC\bin\ktrans.exe" /I"C:\Users\Controls\Rossum_ws\fanuc_driver_exp\include" /I"C:\Users\Controls\Rossum_ws\libindlog\include" /I"C:\Users\Controls\Rossum_ws\libsimplemsg\include" /I"C:\Users\Controls\Rossum_ws\KUnit\include" /I"C:\Users\Controls\Rossum_ws\libmathex\include" /I"C:\Users\Controls\Rossum_ws\libstdex\include" /I"C:\Program Files (x86)\Fanuc\WinOLPC\Versions\V830-1\support" C:\Users\Controls\Rossum_ws\fanuc_driver_exp\src\libssock.kl /ver V8.30-1 /config "C:\Users\Controls\Rossum_ws\fanuc_driver_exp"
  File "C:\ktransw_py-0.2.2\\ktransw.py", line 246
    except ValueError, e:
                     ^
SyntaxError: invalid syntax
ninja: build stopped: subcommand failed.
```

[Rossum_ws.zip](https://github.com/gavanderhoorn/fanuc_driver_exp/files/3004951/Rossum_ws.zip)

**Comment by gavanderhoorn** [comment]
@ReedAJacobsen: I've transferred your issue to `ktransw_py` as it's an issue here, not with `fanuc_driver_exp`.

**Comment by gavanderhoorn** [comment]
@ReedAJacobsen: I'm slightly puzzled by this part of the error message:

```
/config "C:\Users\Controls\Rossum_ws\fanuc_driver_exp"
```

the `/config` argument expects a path to a `robot.ini`, not a directory. Could you re-run `rossum` with the `-v` switch and post the output here?

**Comment by ReedAJacobsen** [comment]
That was my bad, before contacting you i was playing around with different arguments to rossum incase this was the issue. I have now run it with the rossum command from the readme (with -w to overwrite the build file), with similar results. 

```
C:\Users\Controls\Rossum_ws\build>ninja
[1/22] fanuc_driver_exp :: src\rstate_cfg.kl
FAILED: C:/Users/Controls/Rossum_ws/build/rstate_cfg.pc
ktransw.cmd -q -MM -MP -MT C:\Users\Controls\Rossum_ws\build\rstate_cfg.pc -MF C:\Users\Controls\Rossum_ws\build\rstate_cfg.pc.d --ktrans="C:\Program Files (x86)\Fanuc\WinOLPC\bin\ktrans.exe" /I"C:\Users\Controls\Rossum_ws\fanuc_driver_exp\include" /I"C:\Users\Controls\Rossum_ws\libindlog\include" /I"C:\Users\Controls\Rossum_ws\libsimplemsg\include" /I"C:\Users\Controls\Rossum_ws\KUnit\include" /I"C:\Users\Controls\Rossum_ws\libmathex\include" /I"C:\Users\Controls\Rossum_ws\libstdex\include" /I"C:\Program Files (x86)\Fanuc\WinOLPC\Versions\V770-1\support" C:\Users\Controls\Rossum_ws\fanuc_driver_exp\src\rstate_cfg.kl /ver V7.70-1 /config "C:\Users\Controls\Rossum_ws\fanuc_driver_exp\robot.ini"
Traceback (most recent call last):
  File "C:\ktransw_py-0.2.2\\ktransw.py", line 505, in <module>
    main()
  File "C:\ktransw_py-0.2.2\\ktransw.py", line 129, in main
    for key, val in vars(args).iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
[2/22] fanuc_driver_exp :: src\librosfanuc.kl
FAILED: C:/Users/Controls/Rossum_ws/build/librosfanuc.pc
ktransw.cmd -q -MM -MP -MT C:\Users\Controls\Rossum_ws\build\librosfanuc.pc -MF C:\Users\Controls\Rossum_ws\build\librosfanuc.pc.d --ktrans="C:\Program Files (x86)\Fanuc\WinOLPC\bin\ktrans.exe" /I"C:\Users\Controls\Rossum_ws\fanuc_driver_exp\include" /I"C:\Users\Controls\Rossum_ws\libindlog\include" /I"C:\Users\Controls\Rossum_ws\libsimplemsg\include" /I"C:\Users\Controls\Rossum_ws\KUnit\include" /I"C:\Users\Controls\Rossum_ws\libmathex\include" /I"C:\Users\Controls\Rossum_ws\libstdex\include" /I"C:\Program Files (x86)\Fanuc\WinOLPC\Versions\V770-1\support" C:\Users\Controls\Rossum_ws\fanuc_driver_exp\src\librosfanuc.kl /ver V7.70-1 /config "C:\Users\Controls\Rossum_ws\fanuc_driver_exp\robot.ini"
Traceback (most recent call last):
  File "C:\ktransw_py-0.2.2\\ktransw.py", line 505, in <module>
    main()
  File "C:\ktransw_py-0.2.2\\ktransw.py", line 129, in main
    for key, val in vars(args).iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
ninja: build stopped: subcommand failed.
```

**Comment by gavanderhoorn** [comment]
What is the output of `python --version` on your machine?

As noted in the [readme](https://github.com/gavanderhoorn/ktransw_py/blob/5b7761c7d6ac625b65e4dfa5e6c56754a8d24e3e/README.md#requirements), `ktransw` was written for and tested with Python 2.

This:

```
AttributeError: 'dict' object has no attribute 'iteritems'
```

seems to suggest you are trying to run it with Python 3.

If you need Python 3 to be the default on your machine, but do have a Python 2 install available, then you could update [this line](https://github.com/gavanderhoorn/ktransw_py/blob/5b7761c7d6ac625b65e4dfa5e6c56754a8d24e3e/ktransw.cmd#L17) with the absolute path to `python.exe` in your Python 2 installation (don't forget to use `"` around the path if necessary (ie: if it contains spaces)).

**Comment by ReedAJacobsen** [comment]
Nailed it, thanks for the help.

**Comment by gavanderhoorn** [comment]
Np. Glad we solved this.

I've logged #16 to migrate `ktransw` (and `rossum`) to Python 3 at some point in the future (seeing as Python 2 is almost EOL).
